export const figmaScreens = [
  { id: 'onboarding', title: 'Onboarding carousel', flow: 'Welcome' },
  { id: 'login', title: 'Mobile login', flow: 'Auth' },
  { id: 'otp-partial', title: 'OTP partial entry', flow: 'Auth' },
  { id: 'otp-complete', title: 'OTP complete entry', flow: 'Auth' },
  { id: 'setup-profile', title: 'Setup profile', flow: 'Profile' },
  { id: 'home-feed', title: 'Shopping home feed', flow: 'Commerce' },
  { id: 'avatar-wardrobe', title: 'Avatar wardrobe', flow: 'Avatar' },
  { id: 'product-detail', title: 'Product detail', flow: 'Commerce' },
  { id: 'tryon-sheet', title: 'Virtual try-on sheet', flow: 'Try-on' },
  { id: 'ar-product', title: 'AR product preview', flow: 'Try-on' },
  { id: 'vr-headset', title: 'VR headset', flow: 'Try-on' },
  { id: 'create-3d', title: 'Create 3D figure', flow: 'Avatar' },
  { id: 'profile-dashboard', title: 'Profile dashboard', flow: 'Profile' },
  { id: 'empty-wardrobe', title: 'Empty wardrobe', flow: 'Wardrobe' },
  { id: 'wishlist', title: 'Wishlist grid', flow: 'Wishlist' },
  { id: 'empty-wishlist', title: 'Empty wishlist', flow: 'Wishlist' },
  { id: 'search-empty', title: 'Search no results', flow: 'Search' },
  { id: 'recent-searches', title: 'Recent searches', flow: 'Search' },
  { id: 'notifications-empty', title: 'Empty notifications', flow: 'Notifications' },
  { id: 'notifications-activity', title: 'Activity notifications', flow: 'Notifications' },
  { id: 'notifications-promotions', title: 'Promotions notifications', flow: 'Notifications' },
  { id: 'shopping-bag', title: 'Shopping bag', flow: 'Checkout' },
  { id: 'checkout-address', title: 'Checkout address', flow: 'Checkout' },
  { id: 'filters', title: 'Filters', flow: 'Search' },
  { id: 'ai-chat', title: 'Try-on AI chat assistant', flow: 'Support' },
];
